# Generated by Django 2.2.6 on 2020-09-05 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Course number must consists of numbers only')])),
                ('credits', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('finishing_date', models.DateField()),
                ('finishing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Course number must consists of numbers only')])),
                ('credits', models.PositiveIntegerField(default=3)),
                ('total_num_of_students', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('all_statistics_allowed', models.BooleanField(default=False)),
                ('instructor_id', models.PositiveIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist_elective_courses', models.ManyToManyField(blank=True, related_name='student_elective_courses', to='scheduly_app.ElectiveCourse')),
            ],
        ),
        migrations.CreateModel(
            name='UnpreferredLectureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, choices=[('135', '135'), ('24', '24')], max_length=10, null=True)),
                ('starting_time', models.TimeField()),
                ('finishing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('firstChoice', models.CharField(max_length=150)),
                ('secondChoice', models.CharField(max_length=150)),
                ('thirdChoice', models.CharField(max_length=150)),
                ('fourthChoice', models.CharField(max_length=150)),
                ('instructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduly_app.Instructor')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduly_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(to='scheduly_app.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduly_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduly_app.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduly_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='unpreferred_time1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpreferred_time1', to='scheduly_app.UnpreferredLectureTime'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='unpreferred_time2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unpreferred_time2', to='scheduly_app.UnpreferredLectureTime'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructor',
            name='whishlist_courses',
            field=models.ManyToManyField(blank=True, related_name='instructor_courses', to='scheduly_app.Course'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='wishlist_elective_courses',
            field=models.ManyToManyField(blank=True, related_name='instructor_elective_courses', to='scheduly_app.ElectiveCourse'),
        ),
        migrations.AddField(
            model_name='electivecourse',
            name='chosen_by',
            field=models.ManyToManyField(blank=True, related_name='elective_courses_chosen_by', to='scheduly_app.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='chosen_by',
            field=models.ManyToManyField(blank=True, related_name='courses_chosen_by', to='scheduly_app.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='dependants', to='scheduly_app.Course'),
        ),
    ]
